package com.beiming.modules.sys.dict.domain.entity;

import java.util.Date;

public class ResourceScjdglj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.id
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.company_name
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.credit_code
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.registration_number
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String registrationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.phone
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.company_type_code
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String companyTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.company_type_name
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String companyTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.legal_person
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.political_status
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String politicalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.business_address
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String businessAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.registered_capital
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.capital_type
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String capitalType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.registered_capital_dollar
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String registeredCapitalDollar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.paid_in_capital
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String paidInCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.paid_in_capital_dollar
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String paidInCapitalDollar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.total_investment
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String totalInvestment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.total_investment_dollar
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String totalInvestmentDollar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.create_times
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String createTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.operating_begin_time
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String operatingBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.operating_end_time
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String operatingEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.statu
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.license_project
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String licenseProject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.license_type
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String licenseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.police_unit
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String policeUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.main_police_unit
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String mainPoliceUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.register_authority
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String registerAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.main_register_authority
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String mainRegisterAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.business_type
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.business_number
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String businessNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.organization_form
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String organizationForm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.id_card
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.create_time
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.upload_time
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_scjdglj.flag
     *
     * @mbg.generated Wed Apr 22 15:20:05 CST 2020
     */
    private String flag;
}