package com.beiming.modules.sys.dict.domain.entity;

import java.util.Date;

public class resourceWeijianwei {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.id
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.organization
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String organization;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.department
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.person_number
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String personNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.person_name
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String personName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.id_card
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.birthday
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.sex
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.nation
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.work_time
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String workTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.office_phone
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.phone
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.certificate_encoding
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String certificateEncoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.work_flag
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String workFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.specialized_type
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String specializedType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.physician_type
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String physicianType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.management_position
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String managementPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.specialty_skill_zg
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String specialtySkillZg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.specialty_skill_zw
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String specialtySkillZw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.education
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.educational_level
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String educationalLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.specialized
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private String specialized;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.create_time
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_weijianwei.upload_time
     *
     * @mbg.generated Wed Apr 22 13:20:49 CST 2020
     */
    private Date uploadTime;
}